// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: anonymizer.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnonymizerService_AnonymizeBatch_FullMethodName = "/presidio.AnonymizerService/AnonymizeBatch"
)

// AnonymizerServiceClient is the client API for AnonymizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnonymizerServiceClient interface {
	AnonymizeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type anonymizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnonymizerServiceClient(cc grpc.ClientConnInterface) AnonymizerServiceClient {
	return &anonymizerServiceClient{cc}
}

func (c *anonymizerServiceClient) AnonymizeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, AnonymizerService_AnonymizeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnonymizerServiceServer is the server API for AnonymizerService service.
// All implementations must embed UnimplementedAnonymizerServiceServer
// for forward compatibility.
type AnonymizerServiceServer interface {
	AnonymizeBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedAnonymizerServiceServer()
}

// UnimplementedAnonymizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnonymizerServiceServer struct{}

func (UnimplementedAnonymizerServiceServer) AnonymizeBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnonymizeBatch not implemented")
}
func (UnimplementedAnonymizerServiceServer) mustEmbedUnimplementedAnonymizerServiceServer() {}
func (UnimplementedAnonymizerServiceServer) testEmbeddedByValue()                           {}

// UnsafeAnonymizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnonymizerServiceServer will
// result in compilation errors.
type UnsafeAnonymizerServiceServer interface {
	mustEmbedUnimplementedAnonymizerServiceServer()
}

func RegisterAnonymizerServiceServer(s grpc.ServiceRegistrar, srv AnonymizerServiceServer) {
	// If the following call panics, it indicates UnimplementedAnonymizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnonymizerService_ServiceDesc, srv)
}

func _AnonymizerService_AnonymizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnonymizerServiceServer).AnonymizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnonymizerService_AnonymizeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnonymizerServiceServer).AnonymizeBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnonymizerService_ServiceDesc is the grpc.ServiceDesc for AnonymizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnonymizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presidio.AnonymizerService",
	HandlerType: (*AnonymizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnonymizeBatch",
			Handler:    _AnonymizerService_AnonymizeBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anonymizer.proto",
}
