# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anonymizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'anonymizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61nonymizer.proto\x12\x08presidio\"/\n\x0c\x42\x61tchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x10\n\x08language\x18\x02 \x01(\t\")\n\rBatchResponse\x12\x18\n\x10\x61nonymized_texts\x18\x01 \x03(\t2V\n\x11\x41nonymizerService\x12\x41\n\x0e\x41nonymizeBatch\x12\x16.presidio.BatchRequest\x1a\x17.presidio.BatchResponseB\x0eZ\x0c./presidiopbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anonymizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./presidiopb'
  _globals['_BATCHREQUEST']._serialized_start=30
  _globals['_BATCHREQUEST']._serialized_end=77
  _globals['_BATCHRESPONSE']._serialized_start=79
  _globals['_BATCHRESPONSE']._serialized_end=120
  _globals['_ANONYMIZERSERVICE']._serialized_start=122
  _globals['_ANONYMIZERSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
