# Run containers with default ports

services:
  anonymizer:
    build:
      context: ./../anonymizer
      dockerfile: Dockerfile

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
  otel-collector:
    build:
      context: ./../
      dockerfile: demo/collector/Dockerfile
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/:/otelcol/config/
