// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: anonymizer.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_anonymizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anonymizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_anonymizer_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type BatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnonymizedTexts []string               `protobuf:"bytes,1,rep,name=anonymized_texts,json=anonymizedTexts,proto3" json:"anonymized_texts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_anonymizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anonymizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_anonymizer_proto_rawDescGZIP(), []int{1}
}

func (x *BatchResponse) GetAnonymizedTexts() []string {
	if x != nil {
		return x.AnonymizedTexts
	}
	return nil
}

var File_anonymizer_proto protoreflect.FileDescriptor

const file_anonymizer_proto_rawDesc = "" +
	"\n" +
	"\x10anonymizer.proto\x12\bpresidio\"@\n" +
	"\fBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\":\n" +
	"\rBatchResponse\x12)\n" +
	"\x10anonymized_texts\x18\x01 \x03(\tR\x0fanonymizedTexts2V\n" +
	"\x11AnonymizerService\x12A\n" +
	"\x0eAnonymizeBatch\x12\x16.presidio.BatchRequest\x1a\x17.presidio.BatchResponseB?Z=github.com/mxab/otel-presidio/presidioprocessor/client;clientb\x06proto3"

var (
	file_anonymizer_proto_rawDescOnce sync.Once
	file_anonymizer_proto_rawDescData []byte
)

func file_anonymizer_proto_rawDescGZIP() []byte {
	file_anonymizer_proto_rawDescOnce.Do(func() {
		file_anonymizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anonymizer_proto_rawDesc), len(file_anonymizer_proto_rawDesc)))
	})
	return file_anonymizer_proto_rawDescData
}

var file_anonymizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anonymizer_proto_goTypes = []any{
	(*BatchRequest)(nil),  // 0: presidio.BatchRequest
	(*BatchResponse)(nil), // 1: presidio.BatchResponse
}
var file_anonymizer_proto_depIdxs = []int32{
	0, // 0: presidio.AnonymizerService.AnonymizeBatch:input_type -> presidio.BatchRequest
	1, // 1: presidio.AnonymizerService.AnonymizeBatch:output_type -> presidio.BatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anonymizer_proto_init() }
func file_anonymizer_proto_init() {
	if File_anonymizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anonymizer_proto_rawDesc), len(file_anonymizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anonymizer_proto_goTypes,
		DependencyIndexes: file_anonymizer_proto_depIdxs,
		MessageInfos:      file_anonymizer_proto_msgTypes,
	}.Build()
	File_anonymizer_proto = out.File
	file_anonymizer_proto_goTypes = nil
	file_anonymizer_proto_depIdxs = nil
}
